service: my-service

provider:
  name: aws          
  runtime: nodejs18.x
  region: us-east-1 

functions:
  calculate:
    handler: handler.calculate
    events:
      - http:
          path: calculate
          method: post
